### ISSUE TITLE
与facebox 结合的问题

### ISSUE THREAD

**Issue by xubin19939** [610265158/Peppa_Pig_Face_Engine#1]
在您另外一个facelandmark 的工程中，我看到您的训练数据（landmark的输入img）的截取是根据landmark的外框来的，并没有去结合根据人脸检测的框，在peppa pig 的demo 用的landamrk就是用这种数据处理方式得到的吗？
观察到当我把人脸检测的方法换成别的时，精度明显没有用你的人脸检测的做出来的landmark 高，请问您是在训练landmark的数据预处理时参考了人脸检测框吗？

**Comment by xubin19939** [comment]
![image](https://user-images.githubusercontent.com/20274203/65567289-3b99eb00-df88-11e9-80ba-774d118d11f4.png)这张是用你的人脸检测框+你的landmark 的结果
![image](https://user-images.githubusercontent.com/20274203/65567324-5ec49a80-df88-11e9-827e-5f955360d98a.png)这张是用我的人脸检测框+你的landmark的结果
蓝色框就是人脸检测的box

**Comment by 610265158** [comment]
hi，



hi，
训练的时候，是关键点的包围框，但是有random crop，以及多尺度缩放，
demo中，有类似于跟踪的策略，第一次bbox是检测框，后面会判断将框换做关键点的包围框，


其实如果都是自己标注的数据，可以将检测的标注和关键点的输入形式一致，deep learning的一大先验就是数据分布的一致，本质上是这个问题。越一致越好。


祝好
梁子


发件人：xubin19939 <notifications@github.com>
发送日期：2019-09-25 11:19:00
收件人：610265158/Peppa_Pig_Face_Engine <Peppa_Pig_Face_Engine@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[610265158/Peppa_Pig_Face_Engine] 与facebox 结合的问题 (#1)
在您另外一个facelandmark 的工程中，我看到您的训练数据（landmark的输入img）的截取是根据landmark的外框来的，并没有去结合根据人脸检测的框，在peppa pig 的demo 用的landamrk就是用这种数据处理方式得到的吗？
 观察到当我把人脸检测的方法换成别的时，精度明显没有用你的人脸检测的做出来的landmark 高，请问您是在训练landmark的数据预处理时参考了人脸检测框吗？

**Comment by 610265158** [comment]
这两个框的差异没有那么大呀，
除去遮挡的效果应该差不多吧。





发件人：xubin19939 <notifications@github.com>
发送日期：2019-09-25 11:34:45
收件人：610265158/Peppa_Pig_Face_Engine <Peppa_Pig_Face_Engine@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：Re: [610265158/Peppa_Pig_Face_Engine] 与facebox 结合的问题 (#1)
这张是用你的人脸检测框+你的landmark 的结果
 这张是用我的人脸检测框+你的landmark的结果
 蓝色框就是人脸检测的box

**Comment by xubin19939** [comment]
我现在截图的这个结果已经把你box 的tracking 给去掉了，就直接单纯跑的单帧detection+landmark。其实我也很蒙蔽，这种框之间大小 和位置的区别应该在你数据增强的时候以平移，scale这种操作处理过了，所以改变检测框的大小和位置不应该影响这么大，但确实用我的检测框没有用你的检测框效果好。
下面这些图都是上面是你的结果，下面是我的结果，为啥会有这么大的性能差异呢


![image](https://user-images.githubusercontent.com/20274203/65567919-97657380-df8a-11e9-940d-5b03455b515a.png)
![image](https://user-images.githubusercontent.com/20274203/65568262-b284b300-df8b-11e9-9585-8a3aba21a7ca.png)

**Comment by 610265158** [comment]
> 我现在截图的这个结果已经把你box 的tracking 给去掉了，就直接单纯跑的单帧detection+landmark。其实我也很蒙蔽，这种框之间大小 和位置的区别应该在你数据增强的时候以平移，scale这种操作处理过了，所以改变检测框的大小和位置不应该影响这么大，但确实用我的检测框没有用你的检测框效果好。
> 下面这些图都是上面是你的结果，下面是我的结果，为啥会有这么大的性能差异呢
> 
> ![image](https://user-images.githubusercontent.com/20274203/65567919-97657380-df8a-11e9-940d-5b03455b515a.png)
> ![image](https://user-images.githubusercontent.com/20274203/65568262-b284b300-df8b-11e9-9585-8a3aba21a7ca.png)

玄学了，哈哈

**Comment by xubin19939** [comment]
这个玄学的事情还是没有解决，问一下你的facebox 训练就是用的你自己另一个repo 那个facebox 吗？训练的数据就是wideeface？
