### ISSUE TITLE
跟踪问题

### ISSUE THREAD

**Issue by liuhaiyang2018** [610265158/Peppa_Pig_Face_Engine#10]
您好，在调试您的代码的时候发现：当突然遮挡住人脸的时候就会出现bug，貌似是
for i in range(landmarks.shape[0]):
            track.append([np.min(landmarks[i][:, 0]), np.min(landmarks[i][:, 1]), np.max(landmarks[i][:, 0]),
             np.max(landmarks[i][:, 1])])

这块代码的问题，我还在调试，没找到解决方案

**Comment by 610265158** [comment]
> 您好，在调试您的代码的时候发现：当突然遮挡住人脸的时候就会出现bug，貌似是
> for i in range(landmarks.shape[0]):
> track.append([np.min(landmarks[i][:, 0]), np.min(landmarks[i][:, 1]), np.max(landmarks[i][:, 0]),
> np.max(landmarks[i][:, 1])])
> 
> 这块代码的问题，我还在调试，没找到解决方案

我好像刚才fix了，pull一下新的代码，
但是遮挡，这块正确的思路应该在关键点模型中加入二分类来判断。
我会慢慢修正模型的

**Comment by liuhaiyang2018** [comment]
好的，我感觉主要问题在于，当人脸逐渐被遮挡的时候，人脸和特征点区域都在减小，这个时候这行代码就出现bug了
        #### batch predict for face landmark
        landmarks, states = self.face_landmark.batch_call(image, boxes)
![image](https://user-images.githubusercontent.com/36877347/69208278-f233d980-0b8d-11ea-81e8-3a2a5ff69274.png)

**Comment by 610265158** [comment]
是的，是这么个问题，送进去一个None， 没法跑了

不过这个demo是没有对遮挡的处理的，需要升级一下了，后续得加判断

**Comment by liuhaiyang2018** [comment]
![image](https://user-images.githubusercontent.com/36877347/69216906-451a8a80-0ba8-11ea-8a41-291badb172ca.png)
可以在上述位置添加人脸大小判断，去掉batch_call 下的batch_preprocess里面的人脸大小判断

**Comment by 610265158** [comment]
it is correct
