### ISSUE TITLE
 Confused about the code

### ISSUE THREAD

**Issue by xiao-keeplearning** [610265158/Peppa_Pig_Face_Engine#14]
https://github.com/610265158/Peppa_Pig_Face_Engine/blob/b2a39f9f5db13d833c263a6d2aafd4c2e4b41502/lib/core/api/facer.py#L65
Comments on this line of code said ‘calculate the head pose for the whole image‘，but It seems not right when I watch it. This function is for update landmark, do I understand right?

**Comment by 610265158** [comment]
hi，
Sorry about that, it is a mistake. It is correct that this function is for update landmark.
I will correct it.

**Comment by xiao-keeplearning** [comment]
Thanks for your reply, I learned a lot in your project.
