### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by JunGenius** [610265158/Peppa_Pig_Face_Engine#16]
你好,作者。
请问这个demo有C++实现的吗 ？

**Comment by 610265158** [comment]
目前没有，
有空会做

**Comment by JunGenius** [comment]
> 目前没有，
> 有空会做

Ok，谢谢。

**Comment by JunGenius** [comment]
> 目前没有，
> 有空会做

请问下， 我通过C++ tensorflow 加载该模型，可以实现吗 ？

**Comment by 610265158** [comment]
可以的，看看c++的接口，

**Comment by JunGenius** [comment]
> 可以的，看看c++的接口，

你好，大佬。

请问 人脸训练 用的 tf2.0 吗？我可以用 tf 1.13.1 来加载模型吗 ？

`Status status = sess->Run({ {"serving_default_images", input_tensor}, }, { "StatefulPartitionedCall"}, {}, &output_tensor);`

我现在加载模型，一直报错。网上查说因为低版本调用高版本训练的模型，能帮看下，这样加载模型是否正确？ 

不胜感激。

**Comment by JunGenius** [comment]
> > 可以的，看看c++的接口，
> 
> 你好，大佬。
> 
> 请问 人脸训练 用的 tf2.0 吗？我可以用 tf 1.13.1 来加载模型吗 ？
> 
> `Status status = sess->Run({ {"serving_default_images", input_tensor}, }, { "StatefulPartitionedCall"}, {}, &output_tensor);`
> 
> 我现在加载模型，一直报错。网上查说因为低版本调用高版本训练的模型，能帮看下，这样加载模型是否正确？
> 
> 不胜感激。

我尝试使用tf1分支模型，可以加载成功。 想问下，两个模型精度上有差别吗 ？

**Comment by 610265158** [comment]
精度应该没什么太大差异，没具体比对过

**Comment by JunGenius** [comment]
> 精度应该没什么太大差异，没具体比对过

Ok. 非常感谢。。
