### ISSUE TITLE
lr 不随着step 增加而改变

### ISSUE THREAD

**Issue by xubin19939** [610265158/Peppa_Pig_Face_Engine#2]
1.我看到你在实现optimizer的时候是用apply_gradient那些自己去实现的，而不是直接用的minimize，请问为啥要自己写呢？有什么考虑
2.我跑了一下你的training发现lr 并没有在boudaries处变化，global step超过第一个节点150000之后lr还是0.001哎。甚至到了90k 也没变，是不是minize 有什么bug？

**Comment by 610265158** [comment]
> 1.我看到你在实现optimizer的时候是用apply_gradient那些自己去实现的，而不是直接用的minimize，请问为啥要自己写呢？有什么考虑
> 2.我跑了一下你的training发现lr 并没有在boudaries处变化，global step超过第一个节点150000之后lr还是0.001哎。甚至到了90k 也没变，是不是minize 有什么bug？

1.我比较习惯用稍底层的api，可以更自由的控制，没什么特殊考虑
2. 还没发现这个问题，我能看一下超过150000次的log么？

**Comment by xubin19939** [comment]
sorry，我眼花了，是15k ，还远远没到150000，
还有两个个疑问想请教你一下，
1.关于bn的tf.GraphKeys.UPDATE_OPS
我看你代码里写的是train_op = tf.group(apply_gradient_op, *bn_update_ops)，tf.group 里的op执行顺序不是随机的嘛，那这样还能保证bn的mean 和var 会在训练前执行吗？就是说和
 update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
                    with tf.control_dependencies(update_ops):
                        train_op = opt.minimize(loss,global_step=global_step)
这种写法是等价的吗
2.我把你的shufflenet 换成xception，训练大概20个epoch后total loss 在3左右，但完全没学到东西（随机在图上画了一个脸，但不对），但用你的shufflenet训练的话同样的epoch也在20左右的时候loss=4，效果就很好，我比较奇怪为什么loss 收敛的和shufflenet差不多，但结果却那么差，你有什么意见吗
万分感谢~

**Comment by 610265158** [comment]
> sorry，我眼花了，是15k ，还远远没到150000，
> 还有两个个疑问想请教你一下，
> 1.关于bn的tf.GraphKeys.UPDATE_OPS
> 我看你代码里写的是train_op = tf.group(apply_gradient_op, *bn_update_ops)，tf.group 里的op执行顺序不是随机的嘛，那这样还能保证bn的mean 和var 会在训练前执行吗？就是说和
> update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
> with tf.control_dependencies(update_ops):
> train_op = opt.minimize(loss,global_step=global_step)
> 这种写法是等价的吗
> 2.我把你的shufflenet 换成xception，训练大概20个epoch后total loss 在3左右，但完全没学到东西（随机在图上画了一个脸，但不对），但用你的shufflenet训练的话同样的epoch也在20左右的时候loss=4，效果就很好，我比较奇怪为什么loss 收敛的和shufflenet差不多，但结果却那么差，你有什么意见吗
> 万分感谢~

客气了
1. 我觉得mean 和var 在每一步的训练前后进行计算不会有什么区别，因为每一步都累积，是滑动平均，所以我也没有关注这个问题。还有就是tf1的多卡写起来就是很麻烦。

2. 我还没有尽可能的多实验一些结果，但是我也发现了确实shufflenet的效果要好。 目前直觉告诉我是loss设计的问题，这个训练跑起来时间比较长不太好试验。 另外换成xception，结果也不太应该会随机画，可能是哪个地方没有对好。

**Comment by 121786404** [comment]
出一个 shufflenet_v2 0.5的版本吧  ，嵌入式设备上也能跑

**Comment by 610265158** [comment]
> 出一个 shufflenet_v2 0.5的版本吧 ，嵌入式设备上也能跑

shufflenet 的shuffle操作是通过trnaspose reshape做的， tflite不支持维度大于4哎，我在想换一个backbone，或者重新实现一下shuffle 操作，少侠有什么建议么

**Comment by 610265158** [comment]
problem may solved
