### ISSUE TITLE
The TFLite model is unable to run on GPU

### ISSUE THREAD

**Issue by yxchng** [610265158/Peppa_Pig_Face_Engine#25]

**Comment by 610265158** [comment]
why you want to run the tflite model on gpu?

**Comment by yxchng** [comment]
@610265158 Because it is not fast enough on mobile phone. I am currently testing on Qualcomm 730 and it is running at about 20ms per face on CPU. It is problematic when there are many faces. Hopefully it can run faster on GPU. Ideally, <5 ms will be good.

**Comment by 610265158** [comment]
tflite is not fast, bro.

**Comment by yxchng** [comment]
Are MNN and NCNN fast on GPU? Or just faster on CPU?

**Comment by 610265158** [comment]
The model structure is not so fast, you should tune the structure based on your device and your frame work.
