### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'export_dir' 

### ISSUE THREAD

**Issue by SabinaUS** [610265158/Peppa_Pig_Face_Engine#28]
face_detector.py ave me above error: 
self.model = tf.saved_model.load(self.model_path) in this line. In cofig.py as path I gave model/detector
Tensorflow 1.13

**Comment by 610265158** [comment]
Hi,
This is the tf2 api,  if you want tf1. please switch to tf1 branch.

GoodLuck

**Comment by SabinaUS** [comment]
Thank you
