### ISSUE TITLE
视频关键点抖动问题

### ISSUE THREAD

**Issue by HansonXia** [610265158/Peppa_Pig_Face_Engine#3]
您好，
      我看了您给的demo，关键点抖动稳定性比较好。我看在实际代码中，是通过利用前一帧的结果对人脸框和关键点做平滑来进行处理的。我按照同样的方式，在其他视频上测试，抖动稍微好些，但还是有抖动。请问有关视频中关键点抖动问题有什么更好的方法吗？

**Comment by 610265158** [comment]
> 您好，
> 我看了您给的demo，关键点抖动稳定性比较好。我看在实际代码中，是通过利用前一帧的结果对人脸框和关键点做平滑来进行处理的。我按照同样的方式，在其他视频上测试，抖动稍微好些，但还是有抖动。请问有关视频中关键点抖动问题有什么更好的方法吗？

exponential moving average 是可以使结果平滑的，你看看股市的k线图可能就了解是怎么回事了。
其实300w的数据集并不是很多，人数很少，类别及不平衡，多从数据集上下手应该可以，如果有更好的方法我会更新的。
另外你说的视频是在相同的代码上跑的么，如果方便可以传给我一份吗，我来测一下。

**Comment by HansonXia** [comment]
@610265158 我是用自己训练的模型，使用您提供的平滑的方法来做后处理的，发现在视频抖动的稳定性上提升不大。如果做多帧平滑，会有时延。使用lk，会有一些提升，但是提升不大。想请问一下，有没有什么更好的方式来处理视频抖动的稳定性。

**Comment by 610265158** [comment]
> @610265158 我是用自己训练的模型，使用您提供的平滑的方法来做后处理的，发现在视频抖动的稳定性上提升不大。如果做多帧平滑，会有时延。使用lk，会有一些提升，但是提升不大。想请问一下，有没有什么更好的方式来处理视频抖动的稳定性。

这样的话，我认为可能是你的关键点模型训练的还是稍差一些，你可以把后处理关了，看一下我训好的模型的表现

**Comment by HansonXia** [comment]
@610265158 我使用了您提供的预训练模型在相同的视频上跑了一遍，抖动稳定性确实提升很大，基本不怎么抖动。我看了您的关键点repo，训练代码里面好像并没有什么特别的预处理，请问这个是和模型的大小还有训练方式有关吗？我用的是MobileNetV2 0.25X+wing loss+数据蒸馏，请问还有什么提议提高抖动稳定性的trick？

**Comment by 610265158** [comment]
> @610265158 我使用了您提供的预训练模型在相同的视频上跑了一遍，抖动稳定性确实提升很大，基本不怎么抖动。我看了您的关键点repo，训练代码里面好像并没有什么特别的预处理，请问这个是和模型的大小还有训练方式有关吗？我用的是MobileNetV2 0.25X+wing loss+数据蒸馏，请问还有什么提议提高抖动稳定性的trick？

我也不确定哪部分对结果有效，因为没有做消融实验，也没有条件整理成正式的文章可以写，多做数据增强可能是一个点，反正cnn多从数据下手是不会有错的。

**Comment by HansonXia** [comment]
@610265158 看了您关键点训练部分的代码，发现您在预处理时对关键点坐标值做了归一化，网络输出的关键点坐标值也是归一化的坐标值，但是loss使用的是wing loss及默认参数（w=10，epsilon=2.0）。我曾经尝试过归一化和不归一化的方式，发现wing loss原论文上，参数（w=10，epsilon=2.0）对应的是64*64的小图上的绝对坐标值，而非归一化坐标值。请问一下，使用归一化坐标值，参数（w=10，epsilon=2.0）是否需要调整，或者说您是直接使用（w=10，epsilon=2.0）来训练归一化的坐标值的？另外，网络输出的坐标值是否归一化会对结果有什么影响，比如抖动方面？

**Comment by 610265158** [comment]
> @610265158 看了您关键点训练部分的代码，发现您在预处理时对关键点坐标值做了归一化，网络输出的关键点坐标值也是归一化的坐标值，但是loss使用的是wing loss及默认参数（w=10，epsilon=2.0）。我曾经尝试过归一化和不归一化的方式，发现wing loss原论文上，参数（w=10，epsilon=2.0）对应的是64*64的小图上的绝对坐标值，而非归一化坐标值。请问一下，使用归一化坐标值，参数（w=10，epsilon=2.0）是否需要调整，或者说您是直接使用（w=10，epsilon=2.0）来训练归一化的坐标值的？另外，网络输出的坐标值是否归一化会对结果有什么影响，比如抖动方面？

归一化是否影响不太清楚，我觉得不会，0-1 0-160是一个简单的映射关系，CNN很容易拟合，
抖动的原因主要来自数据标注，以及输入数据的信噪比

**Comment by 610265158** [comment]
problem may solved
