### ISSUE TITLE
keypoints.tflite outpute details

### ISSUE THREAD

**Issue by milad-4274** [610265158/Peppa_Pig_Face_Engine#37]
Hi, Thanks for your awesome repository.
I compared your keypoints.tflite model to mediapipe face_landmark.tflite provided by mediapipe.
mediapipe output_details has 2 row containing landmark points and confidence(not sure).

but keypoints.tflite model output_details has 3 row. I don't know what are the first 2 rows but the third row is landmark points.
is the first 2 rows related to confidence? what are they?

**Comment by 610265158** [comment]
hi,
there is no confidence, the others are head pose, and eyes, mouth state;

**Comment by milad-4274** [comment]
Thank you, can you help me to understand what is confidence in landmark? or is it possible to add confidence to this model by retraining it?
As far as I know, confidence is related to face detection not landmark points.

**Comment by 610265158** [comment]
Hi，

In some face landmark model, they treat all the points as independent, so there is a confidence for them.

Simple way, you can regard it as the visibility of each point, same meaning with face detection.
