### ISSUE TITLE
convert tensorflowLite error

### ISSUE THREAD

**Issue by osamu765** [610265158/Peppa_Pig_Face_Engine#4]
I went to convert models into the TensorFlow Lite
keypoints success
but detector get error
packages\tensorflow_core\lite\python\lite.py", line 428, in convert
    "invalid shape '{1}'.".format(_get_tensor_name(tensor), shape_list))
ValueError: None is only supported in the 1st dimension. Tensor 'images' has invalid shape '[None, None, None, None]'.
can help me?
Thinks.

**Comment by 610265158** [comment]
> I went to convert models into the TensorFlow Lite
> keypoints success
> but detector get error
> packages\tensorflow_core\lite\python\lite.py", line 428, in convert
> "invalid shape '{1}'.".format(_get_tensor_name(tensor), shape_list))
> ValueError: None is only supported in the 1st dimension. Tensor 'images' has invalid shape '[None, None, None, None]'.
> can help me?
> Thinks.
because the tflite converter needs the shape to be fixed,
and there is another problem, in the shuffle op , there is a 5 dimensions op, so it still not ok to convert to lite,

though i find the solution, the model is not ok, it will come soon.

**Comment by 610265158** [comment]
> > I went to convert models into the TensorFlow Lite
> > keypoints success
> > but detector get error
> > packages\tensorflow_core\lite\python\lite.py", line 428, in convert
> > "invalid shape '{1}'.".format(_get_tensor_name(tensor), shape_list))
> > ValueError: None is only supported in the 1st dimension. Tensor 'images' has invalid shape '[None, None, None, None]'.
> > can help me?
> > Thinks.
> 
> Because the tflite converter needs the shape to be fixed, but i set it as None,
> And there is another problem. In the shuffle op , there is a 5 dimensions op, so it still not ok to convert to lite.
> 
> Though i find the solution, the model is not ready. Soon, it will be ok.
> 
> Thanks

hi, both the detector and the keypoint model are converted to tflite . please check the pretrained model

**Comment by osamu765** [comment]
have any example to convert  detector to TFLITE?
is possible to make input shape small [1,320,320,3] ?  like [1,160,160,3]?

**Comment by 610265158** [comment]
Please refer to https://github.com/610265158/DSFD-tensorflow/blob/tf2/tools/convert_to_tflite.py

But 160 maybe too small. Because in the net structure, there is a fpn,  which means shape mismatch could happend.

**Comment by osamu765** [comment]
thx

**Comment by osamu765** [comment]
success to convert detector model to TFLITE with input shape [1,160,160,3] 
in case : detect one face in image 
3X+ speeds up for inference
and is possible to reduce the  keypoints*s  input shape? 
think.

**Comment by 610265158** [comment]
Retrain is needed if you want to reduce the input shape for keypoints model.
