### ISSUE TITLE
HeadPose calculation

### ISSUE THREAD

**Issue by elPerro92** [610265158/Peppa_Pig_Face_Engine#5]
Hi, I'm checking the head pose calculation of the face, and I have a problem when with a webcam I change the yaw of my face the pitch and roll change even though my head is not changing pitch and roll (the pitch is increasing for example). I've calibrated my webcam to minimize the distortion from the lenses and changed the D value.
I've seen the "object_pts" variable is an array with the points reference. How did you found these values?
It is possible to change from the "object_pts" which points pick to reduce the error? (for example, add the 4 points of the nose)

**Comment by 610265158** [comment]
> Hi, I'm checking the head pose calculation of the face, and I have a problem when with a webcam I change the yaw of my face the pitch and roll change even though my head is not changing pitch and roll (the pitch is increasing for example). I've calibrated my webcam to minimize the distortion from the lenses and changed the D value.
> I've seen the "object_pts" variable is an array with the points reference. How did you found these values?
> It is possible to change from the "object_pts" which points pick to reduce the error? (for example, add the 4 points of the nose)

Hi，
Yes, the headpose calculation is not so well.
’object_pts‘ should be statistical data，
I think it can help by adding more points.

By the way, the head pose calculation of the face still needs devloping .

Thanks

**Comment by elPerro92** [comment]
Thank you, the main problem is the spikes in values (like the pitch for one frame is 0 degrees and the next frame is 9 degrees) and, when the camera is positioned under the screen, the calculation gives a wrong pitch value when the head is over, for example, 15 degrees, giving a pitch that change not much but the calculation give to me a roll of the head, even though my head is not changing the roll.

Thanks.

**Comment by 610265158** [comment]
> Thank you, the main problem is the spikes in values (like the pitch for one frame is 0 degrees and the next frame is 9 degrees) and, when the camera is positioned under the screen, the calculation gives a wrong pitch value when the head is over, for example, 15 degrees, giving a pitch that change not much but the calculation give to me a roll of the head, even though my head is not changing the roll.
> 
> Thanks.

I feel like that, the headpose calculation has some bug there. It is not correct to calculate the value based on whole image.

**Comment by chikiuso** [comment]
Thanks for your good work, the landmark is really accurate and stable, just the head pose calc seems not robust as said above. Anything I could do to improve the head pose estimation?

**Comment by 610265158** [comment]
> Thanks for your good work, the landmark is really accurate and stable, just the head pose calc seems not robust as said above. Anything I could do to improve the head pose estimation?

Hi, 
By using more keypoints may achieve a better result. 
And a better algorithm.
