### ISSUE TITLE
The meaning of the “states” derived from this keypoint model

### ISSUE THREAD

**Issue by hanans426** [610265158/Peppa_Pig_Face_Engine#7]
hi，I don’t understand the meaning  of the “states” derived from this keypoint model, and why is this variable not used？

**Comment by 610265158** [comment]
> hi，I don’t understand the meaning of the “states” derived from this keypoint model, and why is this variable not used？

hi, it is 4 cls params,(left eye, right eye, mouth open, mouth open widely), 
as we all known that multitask learning can improve the face alignment algorithm.  
However, these params is not that useful, for a face keypoint model.

**Comment by hanans426** [comment]
hi,On the tf1 branch, why can't the "headpose" parameter obtained through keypoint model  be directly used for the headpose prediction?

**Comment by 610265158** [comment]
> hi,On the tf1 branch, why can't the "headpose" parameter obtained through keypoint model be directly used for the headpose prediction?

hi,
You still could get the pose params from the model.

**Comment by hanans426** [comment]
hi，The “headpose” parameters obtained in the model, what is the order of “yaw,roll and pitch”? And why recalculate the head rotation Angle instead of just using these parameters obtained in the “keypoint” model?

修改翻译结果

**Comment by 610265158** [comment]
> hi，The “headpose” parameters obtained in the model, what is the order of “yaw,roll and pitch”? And why recalculate the head rotation Angle instead of just using these parameters obtained in the “keypoint” model?
> 
> 修改翻译结果
hi，
sorry， i forget the order of the three params, but it should be the same with the one that recalculate.     I think you can give it a test. 
There is no specially reason that recalculate the headpose, and there should be littel difference.

**Comment by hanans426** [comment]
ok thank you so much
